name: Continuous Deployment

on:
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '0.14.9'

      - name: Create secrets.yaml
        run: |
          cat <<EOF > secrets.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-secret
          type: Opaque
          stringData:
            DATABASE_USERNAME: '${{ secrets.DATABASE_USERNAME }}'
            DATABASE_HOST: '${{ secrets.DATABASE_HOST }}'
            DATABASE_PORT: '${{ secrets.DATABASE_PORT }}'
            DATABASE_NAME: '${{ secrets.DATABASE_NAME }}'
            DATABASE_PASSWORD: '${{ secrets.DATABASE_PASSWORD }}'
          EOF

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Schedule resource destruction
        run: |
          sleep 3600 # Espera 1 hora (3600 segundos)
          terraform destroy -auto-approve # Destrói os recursos provisionados pelo Terraform
